# Generated by Django 6.0.4 on 2026-04-21 03:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('naran_dep', models.CharField(max_length=15, unique=True, verbose_name='Naran Departamanto')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nre', models.CharField(max_length=11, unique=True, verbose_name='N.R.E')),
                ('naran_estudante', models.CharField(max_length=100, verbose_name='Naran Estudante')),
                ('sexu', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], default='Mane', max_length=4)),
                ('idade', models.IntegerField()),
                ('hela_fatin', models.CharField(blank=True, default='', max_length=50, verbose_name='Hela Fatin')),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('nu_telefone', models.CharField(max_length=8, verbose_name='Numeru Telefone')),
                ('ativu', models.BooleanField(default=True)),
            ],
        ),
    ]
