# Generated by Django 6.0.4 on 2026-04-21 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='ativu',
            new_name='status',
        ),
    ]
