# Generated by Django 6.0.4 on 2026-04-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_ativu_estudante_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='departamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.departamento'),
            preserve_default=False,
        ),
    ]
