# Generated by Django 6.0.4 on 2026-04-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_estudante_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='imajen',
            field=models.FileField(default='', upload_to='imajen'),
            preserve_default=False,
        ),
    ]
