# Generated by Django 6.0.4 on 2026-04-21 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_estudante_imajen'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='data_moris',
            field=models.DateField(default=datetime.datetime(2026, 4, 21, 7, 23, 5, 342169, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
