# Generated by Django 6.0.4 on 2026-04-21 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_estudante_data_moris'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='data_rejistu',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
