# Generated by Django 6.0.4 on 2026-04-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_estudante_data_rejistu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='data_rejistu',
        ),
    ]
